name: "Vault Unseal Actions"
description: "Github Action for Unsealing HashiCorp Vault for Free"
author: "omegion"
inputs:
  address:
    description: "Vault server address"
    required: true
  shard1:
    description: "Vault shard 1"
    required: true
  shard2:
    description: "Vault shard 2"
    required: true
  shard3:
    description: "Vault shard 3"
    required: true
  image:
    description: "Vault shard"
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:
    - name: Run vault-unseal CLI from Github Action REF
      run: |
        docker run --rm -ti ghcr.io/omegion/vault-unseal:${{ inputs.image }} \
          unseal \
          --address=${{ inputs.address }} \
          --shard=${{ inputs.shard1 }},${{ inputs.shard2 }},${{ inputs.shard3 }} \
          --logLevel=debug
      shell: sh