name: Integration Test

on:
#  push:
#  pull_request:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.1.2
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: github
          githubToken: ${{ secrets.GT_VAULT_AUTH_TOKEN }}
          secrets: |
            argocd/data/token admin | ARGOCD_TOKEN ;

      - name: Self test
        id: selftest
        uses: omegion/vault-unseal-action@master
        with:
          address: ${{ secrets.ARGOCD_ADDR }}
          shard: x
          image: latest

