name: Integration Test

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest
        uses: omegion/vault-unseal-action@master
        with:
          address: ${{ secrets.VAULT_ADDR }}
          shard1: x
          shard2: y
          shard3: z
          image: latest

