name: Local

on:
  workflow_dispatch:
    inputs:
      address:
        description: 'Vault server address'
        required: true
        default: 'vault.local'
      shard:
        description: 'Vault shard'
        required: true
        default: 'x'

jobs:
  local_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ./
      - name: Self test
        id: selftest
        uses: omegion/vault-unseal-action@master
        with:
          address: ${{ secrets.VAULT_ADDR }}
          shard1: x
          shard2: y
          shard3: z
          image: latest


