name: Unseal Vault Server Every Hour
on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unseal Vault Server
        uses: omegion/vault-unseal-action@v1
        with:
          address: ${{ secrets.VAULT_ADDR }}
          shard1: ${{ secrets.VAULT_SHARD }}
          shard2: ${{ secrets.VAULT_SHARD }}
          shard3: ${{ secrets.VAULT_SHARD }}
          image: latest